### ISSUE TITLE
Potential theft of intellectual property

### ISSUE THREAD

**Issue by mateusztylec** [13Dominik/engineering_thesis#1]
Hey. I just read your thesis. It looks very similar to a certain one I read earlier. Can you confirm that this work is 100% of your authorship? I have reported the matter to UST AGH for in-depth analysis. 

Best regards.

**Comment by 13Dominik** [comment]
Hey what kind of proof will satisfy you? Could you also send me a 'certain one' that you read?

**Comment by mateusztylec** [comment]
I don't want to give you any hints. You simply copied someone else's work. You don't have to prove anything to me. The matter has been reported. You will have to explain yourself to the rector of AGH. I downloaded your repository to my macbook m4 120gb ram 2TB so I have all the evidence. Setting the repository to private won't help ;). 

Therefore, I am closing the report.

Not best regards

**Comment by 13Dominik** [comment]
Dear Mateusz,
I was aware of that making this repository public will bring down the hater. Hate is not a good way, trust me. I have an offer for you, as you may know I have some experience in private lessons. If you want we can schedule some lessons, where I will try my best to explain to you some basic AI concepts, for example like my thesis. I can make a special price for you.

**Comment by mateusztylec** [comment]
yeah, have heard about your lessons. i talked with one of your student. he said that you still can't implement komiwojażer properly.

so iam not interested, get lost, fck u
ticket is closed which means you should not reply.
!(best regards)

**Comment by mateusztylec** [comment]
<img width="450" alt="image" src="https://github.com/13Dominik/engineering_thesis/assets/79941376/4cd990a8-bfde-4d44-9239-05c32397e834">
<img width="450" alt="image" src="https://github.com/13Dominik/engineering_thesis/assets/79941376/1b32a607-fe4f-4c9a-ae19-c95ab9bb7f7a">

**Comment by 13Dominik** [comment]
Komiwojażer? Stop disrespecting me, I wrote code for TSP on my own, and it was done in C++ (hard programming language, you may not know). I starred my own repository - that's true but I did it because it is so great.
